

app:
  repertoire:
  date-analyse:
  fichier-donnees:
  pushgateway:
    url: localhost:9091
    actif: true
    job-name: my-spring-boot-app-test
    prefix-name: loganalysebtest
  files:
    -
      path: build.gradle
      nomMetrics: buildgradle
    -
      path: build/libs/loganalyseb-0.0.1-SNAPSHOT.jar
      nomMetrics: loganalyseb_jar
    -
      path: ${app.files2.path}
      nomMetrics: ${app.files2.nomMetrics}
      typeMetrics: ${app.files2.typeMetrics}
      debutFichier: ${app.files2.debutFichier}


management:
  metrics:
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          job: my-spring-boot-app
          push-rate: 10s  # fréquence d’envoi





